CREATE TABLE CUSTOMERS(
C_NUM INT PRIMARY KEY ,
C_NAME NVARCHAR(20),
C_PHONE nvarchar(20),
C_ADDRESS NVARCHAR(50),
C_DOB NVARCHAR(20),
C_GENDER NVARCHAR (10)
)

CREATE TABLE SELLER(
S_NUM INT PRIMARY KEY,
S_NAME NVARCHAR(20),
S_DOB NVARCHAR(10),
S_PHONE NVARCHAR(20),
S_ADDRESS NVARCHAR(50),
S_GENDER NVARCHAR (10),
S_PASS NVARCHAR(20)
)

CREATE TABLE MANUFACTURERS(
M_ID INT ,
M_MANUFACT NVARCHAR(20),
M_ADDRESS NVARCHAR(50),
M_PHONE NVARCHAR(20),
M_JDATE NVARCHAR(10),
PRIMARY KEY (M_ID, M_MANUFACT)
)

CREATE TABLE MEDICINES(
M_NUM INT PRIMARY KEY,
M_NAME NVARCHAR(20),
M_TYPE NVARCHAR(20),
M_QUANTITY INT,
M_PRICE INT,
M_MANID INT,
M_MANNAME NVARCHAR(20),
FOREIGN KEY (M_MANID, M_MANNAME) REFERENCES MANUFACTURERS(M_ID, M_MANUFACT)
)

INSERT INTO CUSTOMERS VALUES (1,'AHMED','03434777283','D-32 NAZIMABAD','2000-12-4','MALE') 
INSERT INTO CUSTOMERS VALUES (2,'NAVROZ','02239337902','A-17 GULBERG ','1995-5-9','MALE')
INSERT INTO CUSTOMERS VALUES (3,'NADIA','03345288941','B-12 NEW KARACHI','1993-11-17','FEMALE')

INSERT INTO MANUFACTURERS VALUES (500,'DUBAI','Al Hamraniyah','94563746231','2010-3-12')
INSERT INTO MANUFACTURERS VALUES (501,'INDIA','Pahar Ganj','97634450032','2015-9-20')
INSERT INTO MANUFACTURERS VALUES (502,'CANADA','1124 Yonge Street','91465775933','2011-2-11')

INSERT INTO MEDICINES VALUES (101,'DOLOZOX','PAIN KILLER',70,50,500,'DUBAI')
INSERT INTO MEDICINES VALUES (102,'ZERODOL','TABLET',100,30,501,'INDIA')
INSERT INTO MEDICINES VALUES (103,'CHLOROQUINE','INJECTIONS',60,20,502,'CANADA')

INSERT INTO SELLER VALUES (4,'SHANILLA','1994-02-15','03563546422','SAFORA','FEMALE','123')
INSERT INTO SELLER VALUES (5,'JUNAID','1996-08-25','03334667229','GULZAR E HIJIRI','MALE','ABC')
INSERT INTO SELLER VALUES (6,'AKRAM','1992-10-28','02267493321','GULSAN E HADEED','MALE','XYZ')


SELECT * FROM CUSTOMERS
SELECT * FROM SELLER
SELECT * FROM MEDICINES
SELECT * FROM MANUFACTURERS

CREATE VIEW CUSTOMER_INFO
AS 
SELECT C_NUM AS NUM, C_NAME AS NAME,C_PHONE AS PHONE,C_ADDRESS AS ADDRESS, C_DOB  AS DOB, C_GENDER AS GENDER
FROM CUSTOMERS

SELECT * FROM CUSTOMER_INFO

CREATE VIEW MANUFACT_INFO
AS
SELECT M_ID AS ID, M_MANUFACT AS MANUFACT, M_ADDRESS AS ADDRESS, M_PHONE AS PHONE, M_JDATE AS JDATE
FROM MANUFACTURERS

SELECT *FROM MANUFACT_INFO

CREATE  VIEW MEDICINES_INFO
AS 
SELECT M_NUM AS NUM, M_NAME AS NAME, M_TYPE AS TYPE, M_QUANTITY AS QUANTITY, M_PRICE AS PRICE, M_MANID AS MANID, M_MANNAME AS MANAME
FROM MEDICINES

SELECT *FROM MEDICINES_INFO

CREATE VIEW SELLER_INFO
AS
SELECT S_NUM AS NUM, S_NAME AS NAME, S_DOB AS DOB, S_PHONE AS PHONE, S_ADDRESS AS ADDRESS, S_GENDER AS GENDER, S_PASS AS PASS
FROM SELLER

SELECT * FROM SELLER_INFO



